---
name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  eslint:
    name: eslint
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v3
    - name: install node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install Node.js dependencies
      run: npm ci
    - name: Unit testing with Chai
      run: npm run test:ci
