---
name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  typescript-ci:
    name: typescript-ci
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v3
    - name: install node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install Node.js dependencies
      run: npm ci
    - name: Unit testing with Chai
      run: npm run test:ci
